### ISSUE TITLE
How to build the project ?

### ISSUE THREAD

**Issue by c128128** [Dashlane/apple-apps#3]
Thank you for going open source.

But ...

The instructions how to build the project are missing.
The `xcodeproj` is missing.

**Comment by irew** [comment]
Hi @c128128!

Thanks for raising this topic. Dashlane has made the mobile app source code available, though it is not strictly open source. The aim is to make the code base available to scrutiny. This was mentioned here:

https://blog.dashlane.com/mobile-code-now-publicly-available/

So there is no configuration, just the source code, and this is on purpose.
