### ISSUE TITLE
iOS Widget Localization DE

### ISSUE THREAD

**Issue by Jersyfi** [Dashlane/apple-apps#5]
I have already reported an issue on iOS where the German translation had UI problems. It seems that you simply set a maximum size for the fields, which means that you can't read the text because it's too small.

![20230227_191608954_iOS](https://user-images.githubusercontent.com/64214261/221660975-5a912b19-bf7c-40ec-914e-a72cceb67899.png)

I couldn't found where the Translations are stored because i'm not used to Swift but i can provide the translation and the exact definition.

### Title
Translation from `Passwortintegritätsbewertung ` to `Passwortintegrität`
Definition: `internal static let widgetTitle = L10n.tr("Localizable", "widgetTitle", fallback: "Password Health Score")`

### Reused
Translation from `Wiederverwendet` to `Mehrfach` or `Erneut`
Definition: `internal static let passwordHealthModuleReused = L10n.tr("Localizable", "PASSWORD_HEALTH_MODULE_REUSED", fallback: "Reused")`

**Comment by Jersyfi** [comment]
An answer would have been nice but thank you for fixing the issue.

**Comment by irew** [comment]
> An answer would have been nice but thank you for fixing the issue.

Hey @Jersyfi sorry about that! And thanks for the heads up! We've only just recently made our source code available, and we're not yet organised about monitoring and answering. We appreciate the help!
