### ISSUE TITLE
3P security audits

### ISSUE THREAD

**Issue by randomishwalk** [Dashlane/apple-apps#8]
Could you please add these to the relevant repos here? I'm including all the various clients as well as any server infrastructure & proprietary cryptography that Dashlane relies upon.

Thank you

**Comment by randomishwalk** [comment]
Examples from your competitors:

- [1Password](https://bucket.agilebits.com/security/1Password_Security_Audit_Report_Onica.pdf)
- [Bitwarden](https://community.bitwarden.com/t/increase-third-party-audits-and-penetration-testing-routinely-vary-auditors/47888/15)

**Comment by Mikescops** [comment]
Hello,

You can find all security related resources on our dedicated website: https://trust.dashlane.com .

Thanks.
